//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCER.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluarTecnico
    {
        public int ID_Evaluacion { get; set; }
        public string RUT_Cliente { get; set; }
        public int ID_Orden { get; set; }
        public int Puntuacion { get; set; }
        public string Comentario { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual Orden_Trabajo Orden_Trabajo { get; set; }
    }
}
