//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCER.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDControl : DbContext
    {
        public BDControl()
            : base("name=BDControl")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<Equipo> Equipo { get; set; }
        public DbSet<EvaluarTecnico> EvaluarTecnico { get; set; }
        public DbSet<Orden_Trabajo> Orden_Trabajo { get; set; }
        public DbSet<Recepcion> Recepcion { get; set; }
        public DbSet<TipoPago> TipoPago { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
