//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCER.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden_Trabajo
    {
        public Orden_Trabajo()
        {
            this.EvaluarTecnico = new HashSet<EvaluarTecnico>();
        }
    
        public int ID_Orden { get; set; }
        public string RUT_Usuario { get; set; }
        public int ID_Recepcion { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public int Precio { get; set; }
        public string Estado_pago { get; set; }
        public int ID_TipoPago { get; set; }
    
        public virtual ICollection<EvaluarTecnico> EvaluarTecnico { get; set; }
        public virtual Recepcion Recepcion { get; set; }
        public virtual TipoPago TipoPago { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
