//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoCER.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPago
    {
        public TipoPago()
        {
            this.Orden_Trabajo = new HashSet<Orden_Trabajo>();
        }
    
        public int ID_pago { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Orden_Trabajo> Orden_Trabajo { get; set; }
    }
}
